--- 
title: "A Learning Guide to R: data, analytical, and programming skills."
author: "Remko Duursma"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "The HIERmanual has new clothes."
---



```{r echo=FALSE, message=FALSE, warning=FALSE}
# Preamble
library(knitr)
knit_theme$set("earendel")
opts_chunk$set(background="grey94")

# Avoid long output
hook_output = knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
    if (!is.null(n <- options$out.lines)) {
        x = unlist(stringr::str_split(x, "\n"))
        if (length(x) > n) {
            # truncate the output
            x = c(head(x, n), "....\n")
        }
        x = paste(x, collapse = "\n")  # paste first n lines together
    }
    hook_output(x, options)
})

# Fix ugly tilde
library(knitr)
hook_source <- knit_hooks$get('source')
knit_hooks$set(source = function(x, options) {
  txt = hook_source(x, options)
  # extend the default source hook
  gsub('~', '\\\\mytilde', txt)
})

# Figure size templates
opts_template$set(smallsquare = list(fig.height = 5, fig.width = 5, 
                                     fig.align="center", out.width=".6\\linewidth"),
                  wide        = list(fig.height = 5, fig.width = 9, 
                                     fig.align="center", out.width=".8\\linewidth"),
                  largesquare = list(fig.height = 8, fig.width = 8, 
                                     fig.align="center", out.width=".8\\linewidth"),
                  extrawide = list(fig.height = 4, fig.width = 10,
                                     fig.align="center", out.width=".9\\linewidth"))

# Fonts
source("R/theme_datapelikaan.R")
library(showtext)
font_add_google(name = "Lato", family = "Lato", regular.wt = 400, bold.wt = 700)
library(ggplot2)
theme_set(theme_datapelikaan(base_family = "Lato"))
knitr::opts_chunk$set(fig.showtext = TRUE, dev="svg")


```


# Preface

Focus on 'good' R code, good practice in programming. Code snippets, how do I do X? Focus on *useful* tools, direct practical application. More practical approach than some other books, requiring no math/stat/computer science background. 

Meant as a guide while learning R. You will also learn many new packages, tips and tricks from the internet (especially Stackoverflow). But you need a solid foundation, otherwise those examples and tricks make little sense, and you find yourself making mistakes a little too often. 

This book is not an introduction to statistical theory, although sometimes we repeat a little theory to be able to make sense of R output. This book should not be the first statistics book you read. Instead, this book shows you how to implement many useful data analysis routines in R. We really assume that you have already learned statistics elsewhere and are here to learn how to actually do the analyses with R.

We have learned from experience that data practictioners, that means scientists and everyone else who has an interest in learning from data, do not learn statistical analyses by studying the underlying theory. They learn from doing, and from using examples written by others who have learned by doing. For this reason the book in front of you is largely a compendium of examples. We have chosen the examples and the exercises in the hope that they resemble real-world problems. 

We have designed this book so it can be used for self-study. The exercises at the end of each chapter aim to test important skills learned in the chapter. Before you start on the exercises, read through the text, try to run the examples, and play around with the code making small modifications. We have also placed many *Try it yourself* boxes throughout the text to give you some ideas on what to try, but try to be creative and modify the examples to see what happens.

An index with the functions and packages used is provided at the end of this book.

**How did I choose all the packages used here?**

From experience and meeting criteria which include:
- Easiest syntax: usually we can come up with many ways to solve a particular problem in R. I like to choose the easiest to learn syntax, but especially if **the code is understandable by reading it**. 
- Actively maintained (although this is not necessary)
- I like to use base R when I can, although end up using a lot of `tidyverse` packages, since they include so many nice inventions. Keeping dependencies to a minimum is one of the **R programmer's tips** (see Section)
- Sometimes the presence of an active user base (indicated by use in blogs, stackoverflow, publications) is a positive indicator for a package. 


```{block2 type="rmdreading"}
Read these other books for deeper into statistical theory. 
- ISLR great book for machine learning intro, regression (though not non-linear, mixed-effects)
- predictive modeling (Kuhn) better at predictive modeling with R (caret)
- car better at regression methods (but no non-linear)
```


**R Programming: Top Tips**


Key indicators of 'good code':
- reproducibility (code works later and on another machine)
- maintainability (easy to modify and adapt existing code, keep code working)
- robustness (harder to make mistakes when coding)
- readability (others can read your code)


What to do:
1. Keep dependencies to a minimum (use less packages)
1. Shorter code is better, but not even shorter
1. Avoid code repetition. Write functions.
1. Do not keep blocks of commented code, delete it!
1. Write many comments
1. Use git version control
1. Use good names for variables, columns, datasets. Longer names are OK.




